### ISSUE TITLE
Setting converter options to prevent metadata loss?

### ISSUE THREAD

**Issue by timnarr** [MRFD/kirby-webp#10]
Hi Marijn,

I want to prevent that my images looking washed out, because of a missing color profile and thats why I wonder if there is a solid way to pass options through to the converter?

**For example:** 
`"metadata" => "all"` as option array to disable this `-strip` command, which is removing color profiles and other metadata.
https://github.com/rosell-dk/webp-convert/blob/master/src/Convert/Converters/ImageMagick.php#L154

The `-strip` command is decribed here:
https://imagemagick.org/script/command-line-options.php#strip

This `-strip` command is also running in the default Kirby "ImageMagick" thumb driver. I made a copy of this, removed the `-strip` command and moved it in a simple plugin. The Kirby generated images/jpegs are looking better now, but the webp images are still loosing their color profile. 

Thank you for your time and help.
Tim

**Comment by MRFD** [comment]
Hi Tim, I am working on the implementation for passing through the conversion options. I have this working via the plugin options. Only I am running into some problems in verifying that it is working correctly.

With the `'metadata' => 'all'` option enabled, I see that Adobe Bridge lists the WebP file as `Color Profile: Untagged`, while the source file lists as `sRGB IEC61966-2.1`. When I use command line tools I see the following:

With exiftool:
```bash
> exiftool test.webp | grep -i profile
[...]
Profile Description             : sRGB IEC61966-2.1
```

With Imagemagick identify:
```bash
> identify -verbose test.webp | grep -i icc
identify: CorruptImageProfile `test.webp' (XMP) @ warning/profile.c/ValidateXMPProfile/1916.
    Profile-icc: 3144 bytes
    icc:copyright: Copyright (c) 1998 Hewlett-Packard Company
    icc:description: sRGB IEC61966-2.1
    icc:manufacturer: IEC http://www.iec.ch
    icc:model: IEC 61966-2.1 Default RGB colour space - sRGB
```

My knowledge of colour profiles is limited. Is this the desired functionality?

**Comment by timnarr** [comment]
Hi Marijn,

To be honest, I don't know either, if this is the correct behavior.

Somehow it looks like it's fine that way. Both commands return a color profile, but "Imagemagick identify" also shows an error at the same time?! ```identify: CorruptImageProfile `test.webp' (XMP) @ warning/profile.c/ValidateXMPProfile/1916.```

So far I had checked it only visually.
Can I somehow test a first draft or can support this in another way?

**Comment by MRFD** [comment]
I am still working on some tests. It seems that the ICC profile is only present if it is explicitly included when exporting the image (from Photoshop, for example).

When minifying jpg files, this metadata is also removed.

If no profile is present in the image, it is [assumed](https://developers.google.com/speed/webp/docs/riff_container#color_profile) that it is an sRGB file.

I have also verified the converted webp files. This seems to work correctly, despite the strange message in Imagemagick identify.

```bash
> webpinfo test.webp
File: test.webp
RIFF HEADER:
  File size:  13936
Chunk VP8X at offset     12, length     18
  ICCP: 1
  Alpha: 0
  EXIF: 1
  XMP: 1
  Animation: 0
  Canvas size 1022 x 704
Chunk ICCP at offset     30, length   3152
Chunk VP8  at offset   3182, length   7864
  Width: 1022
  Height: 704
  Alpha: 0
  Animation: 0
  Format: Lossy (1)
Chunk EXIF at offset  11046, length     94
Chunk XMP  at offset  11140, length   2796
No error detected.
```

I can also report that the other metadata like EXIF and XMP is preserved with `'metadata' => 'all'`.
