### ISSUE TITLE
Error for SVG upload

### ISSUE THREAD

**Issue by aristotheme** [MRFD/kirby-webp#2]
Hi!

I really love your plugin but when I upload SVG or GIF file then I got this message; 

![error](https://user-images.githubusercontent.com/8405467/89680943-a92edb80-d8fc-11ea-9beb-6d953f23447e.jpg)

How can I fix it? Could you please help me?

**Comment by MRFD** [comment]
Hi @aristotheme, the webp conversion is only compatible with jp(e)g and png files. I modified the code so that you won't get this message when uploading gif and svg files. Thanks for opening this issue!

**Comment by aristotheme** [comment]
Woww you are amazing. It works like a charm! :) Thank you so muchhhh!
