### ISSUE TITLE
Hi MRFD

### ISSUE THREAD

**Issue by aristotheme** [MRFD/kirby-webp#5]
I uploaded svg  I got this error on frontend 
![Kirby-CMS-Debugger](https://user-images.githubusercontent.com/8405467/100825876-1e08c100-346a-11eb-9860-d1431700f10a.jpg)

I use this url path;

```
data-src="<?= $image->webpObject()->url() ?>"
data-srcset="<?= $image->srcsetWebp([640, 960, 1920]) ?>"
```

Could you please help about this issue?

**Comment by MRFD** [comment]
Hi, it seems that the file conversion while uploading via the Panel was not successful. I have modified the code to return to the original image object, as a fallback. Please check that images have been uploaded correctly through the Panel.

**Comment by aristotheme** [comment]
Thank you so much! :)
