### ISSUE TITLE
srcset doesn’t work using the webp method

### ISSUE THREAD

**Issue by lkssmnt** [MRFD/kirby-webp#8]
Hi!
Am I missing something, or is this not working as intended?

Example:

```
if($image = $page->testimg()->toFile()) {
     echo $page->testimg()->toFile()->webp('class', $image->alt(), [300, 800, 1024]);
}
```

is giving me just this and ignores the srcset array:

```
<img alt="alt text" class="classname" src="path/image.webp">
```

Would it also be possible to use a predefined srcsets from the config.php like so:
```
    'thumbs' => [
      'srcsets' => [
        'default' => [
          '800w' => ['width' => 800, 'quality' => 80],
          '1024w' => ['width' => 1024, 'quality' => 80],
          '1440w' => ['width' => 1440, 'quality' => 80],
          '2048w' => ['width' => 2048, 'quality' => 80]
        ]
      ]
    ]
```

Thank you very much for your work!

**Comment by MRFD** [comment]
Hi,

Thank you for your comment. I have solved the problem in the latest version. I have also added an extra entry in the documentation about using predefined srcset.


```php
# Presets predefined in config.php

return [
  'thumbs' => [
    'srcsets' => [
            'default' => [300, 800, 1024],
            'cover' => [800, 1024, 2048]
        ]
  ]
];
```

```php

# Usage in templates

if ($image = $page->image('cover.jpg')) {
    echo $image->webp('some-class', 'Image description', 'cover');
}

```

Please note that the default value should be called as follows: `$image->webp('some-class', 'Image description', 'default')`.
