### ISSUE TITLE
TypeError for images in draft page 

### ISSUE THREAD

**Issue by timnarr** [MRFD/kirby-webp#9]
Hi Marijn,

I found an unexpected behavior.... 
I get a TypeError when I open a page in draft state. Everything works fine, when the page is unlisted or listed. Here is a screenshot:
![TypeError](https://user-images.githubusercontent.com/3532570/117867420-a486c180-b298-11eb-9139-1c0e5aeed6fa.png)

Nevertheless... Thank you very much for your work. I've been using the plugin in development for a while now and it works great. Soon I will launch my new site and I wonder if there is any way to give something back to you? Like a Buy-me-coffee link? 

Thank you.
Tim

**Comment by MRFD** [comment]
Hi Tim, thanks for your kind words! 

Due to the way the Kirby draft pages work, the `File` object could not be retrieved. I have now fixed this in the latest release. I also added the option for a donation in the readme. 

Good luck with your new site!

Thanks,
Marijn

**Comment by timnarr** [comment]
Works great for me now. Thank you :)
